Updated code to work with exported tasks
sindresolh/cpp pull request #29
Opened 2022-01-27 10:24 UTC by henrikrn-ntnu

### Adjustments:
- Task reducer gets tasks from json file instead of JS file
- Some changes to code block object: {code, category, id, indent}
- Updated code and tests to work with this structure
- Include indent and id when creating task
- Export as json instead of csv

2022-01-28 11:48 UTC, sindresolh commented
Virker ikke som det nye formatet tar hensyn til:

1. Korrekt løsning av oppgaven
2. Flere tasks i et taskset

Se Sidebar.js og handleSubmit()

2022-01-28 11:48 UTC, sindresolh requested changes
Se kommentaren ovenfor

2022-01-31 08:38 UTC, sindresolh commented
Er denne good nå?
Kunne du vist hvordan man kan ha flere tasks i en taskset med dette formatet?

2022-01-31 08:48 UTC, henrikrn-ntnu commented
Ja, skal være fikset nå. Se melding på Facebook angående å legge til flere tasks

2022-01-31 09:47 UTC, merged