Hvem er i lobbyen?
sindresolh/cpp pull request #30
Opened 2022-01-27 10:54 UTC by sindresolh

En liten update for å vise hvilke players som er i lobbyen

Har fortsatt ikke klart å sette nicknames på spillerene :'(

2022-01-28 11:46 UTC, henrikrn-ntnu requested changes
Bra jobbet igjen! La en kommentar om at vi må ta hensyn til at en bruker ikke fyller ut nickname. Isåfall blir det blankt i spillet. Evt kan bi bruke substring av id hvis nick er blankt hvis vi ikke skal "tvinge" brukeren å skrive nickname før de joiner. Isåfall kan vi jo bare disable "join game" knappen til de har skrevet inn noe.

2022-01-28 11:46 UTC, henrikrn-ntnu commented on app/src/components/Lobby/Lobby.js
> +    for (var p of players) {
Småpirk, men kan sikkert bruke "let" istedenfor var

2022-01-28 11:46 UTC, henrikrn-ntnu commented on app/src/components/Lobby/Lobby.js
> +      (function waitForNick() {
Vi burde kanskje sjekke om nick er blankt i tilfelle noen ikke skriver noe i nickname (hvis vi skal tillate det da). Isåfall blir det kanskje å bruke substring av id istedenfor nick?

2022-01-28 12:34 UTC, sindresolh commented on app/src/components/Lobby/Lobby.js
> +    for (var p of players) {
trodde jeg måtte bruke var i for loop, der lærte jeg noe nytt :)

2022-01-28 12:35 UTC, sindresolh commented on app/src/components/Lobby/Lobby.js
> +      (function waitForNick() {
Jeg tenker at vi ikke tillater blankt. Skal lage en form validator senere som sanitizer input

2022-01-28 12:39 UTC, sindresolh commented on app/src/components/Lobby/Lobby.js
> +      (function waitForNick() {
Kan forsåvidt legge inn at dersom det blir blankt av en eller annen grunn så blir det id uansett

2022-01-31 08:33 UTC, sindresolh commented
Hei, nå har jeg gjort endringer etter tilbakemeldinger =) Gjerne se over en gang til

- Fallback til id dersom nickname er tomt
- let > var

2022-01-31 08:39 UTC, henrikrn-ntnu commented
>

2022-01-31 08:39 UTC, closed without merging

2022-01-31 08:40 UTC, henrikrn-ntnu commented
> 

Virker bra, bare å merge!