Code block hover
sindresolh/cpp pull request #42
Opened 2022-02-07 14:55 UTC by sindresolh

## Hva er nytt?
- Nytt design når du joiner et nytt game
- Hover på codeblock og modalknapper
- Oppdatert feedback på submit til å ta hensyn til indenting og lengre kodelinjer

2022-02-07 15:22 UTC, henrikrn-ntnu requested changes
Veldig bra! Føles mer "proft" nå, både med lobby og feedback på knapper/blocks.

Jeg hadde et forslag på hvordan modalHeigth blir satt, men du kan vurdere selv om du vil bruke det :)

2022-02-08 11:08 UTC, sindresolh commented on app/src/components/Sidebar/SidebarModal/SidebarModal.js
> +  if (showFeedback === 'block') {
Ja, det er bedre :) vi bør ha en øvre grense ja

2022-02-08 11:26 UTC, henrikrn-ntnu approved these changes

2022-02-08 11:27 UTC, merged

2022-02-08 11:27 UTC, sindresolh commented
Da har jeg lagt til endringene :)